[project]
name = "panda-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.12",
    "panda>=0.3.1",
    "pydantic>=2.11.5",
    "streamlit>=1.45.1",
]
